#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")"

if ! [[ -e ~/.emacs ]]; then
    ln -s "$PWD/.emacs" ~/.emacs
fi

if ! [[ -e ~/.screenrc ]]; then
    ln -s "$PWD/.screenrc" ~/.screenrc
fi

echo "export ALTERNATE_EDITOR=''" >> ~/.bashrc
echo "export EDITOR='emacsclient -c -nw'" >> ~/.bashrc
echo "alias emacs='emacsclient -c -nw'" >> ~/.bashrc
echo "export FZF_DEFAULT_OPTS='--height 100% --layout=reverse'" >> ~/.bashrc
echo "[ -f /usr/share/fzf/shell/key-bindings.bash ] && source /usr/share/fzf/shell/key-bindings.bash"  >> ~/.bashrc
